CREATE TABLE IF NOT EXISTS admin_ai_memory (
    user_id BIGINT UNSIGNED NOT NULL PRIMARY KEY,
    context_json LONGTEXT NOT NULL,
    output_log_json LONGTEXT NOT NULL,
    last_instruction TEXT NULL,
    model VARCHAR(120) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_admin_ai_memory_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
