<?php
declare(strict_types=1);
$root = dirname(__DIR__);
$source = json_decode(file_get_contents($root.'/docs/jobsearch/help/source.json'), true, 512, JSON_THROW_ON_ERROR);
$seeds = $source['ui']; $definitions = [];
foreach ($source['topics'] as $topic) {
    $definition = array_intersect_key($topic, array_flip(['id','pages','category','links']));
    $definition['step_count'] = count($topic['text']['de-CH']['steps']);
    $definition['tip_count'] = count($topic['text']['de-CH']['tips']);
    $definitions[] = $definition;
    foreach ($source['locales'] as $locale) {
        $text = $topic['text'][$locale];
        foreach (['title','summary'] as $field) { $seeds['help.v2.'.$topic['id'].'.'.$field][$locale] = $text[$field]; }
        foreach (['steps','tips'] as $field) {
            foreach ($text[$field] as $i => $value) { $seeds['help.v2.'.$topic['id'].'.'.$field.'.'.$i][$locale] = $value; }
        }
    }
}
ksort($seeds);
$block = '// BEGIN GENERATED HELP' . "\n";
$block .= 'function helpTranslationSeeds(): array' . "\n{\n    static \$catalog = ".var_export($seeds,true).";\n    return \$catalog;\n}\n\n";
$block .= 'function helpTopicDefinitions(): array' . "\n{\n    return ".var_export($definitions,true).";\n}\n";
$block .= '// END GENERATED HELP';
$block = preg_replace('/[ \\t]+$/m', '', $block);
$path = $root.'/public/index.php';
$php = str_replace("\r\n","\n",file_get_contents($path));
$php = preg_replace_callback('~// BEGIN GENERATED HELP.*?// END GENERATED HELP~s', static fn() => $block, $php, 1, $count);
if ($count !== 1) { throw new RuntimeException('Generated-help markers missing'); }
$outputs = [$path => $php];
foreach ($source['locales'] as $locale) {
    $md = '# '.$seeds['help.hero_title'][$locale]."\n\n";
    $md .= '<!-- Generated by tools/build_help.php from source.json; edit the source, not this file. -->'."\n\n";
    $md .= 'Version '.$source['version'].' | '.$source['reviewed']."\n\n";
    foreach ($source['topics'] as $topic) {
        $text = $topic['text'][$locale];
        $md .= '## '.$text['title']."\n\n".$text['summary']."\n\n";
        foreach ($text['steps'] as $i=>$step) { $md .= ($i+1).'. '.$step."\n"; }
        $md .= "\n".implode("\n\n",$text['tips'])."\n\n";
        $links = [];
        foreach ($topic['links'] as $page) {
            [$basePage, $anchor] = array_pad(explode('#', $page, 2), 2, '');
            foreach ($source['topics'] as $target) {
                if (in_array($basePage, $target['pages'], true)) {
                    $url = 'https://jobs.jema.business/?page='.$basePage.'&lang='.$locale.($anchor !== '' ? '#'.$anchor : '');
                    $label = $source['ui']['help.link.'.$basePage][$locale] ?? $target['text'][$locale]['title'];
                    $links[] = '['.$label.']('.$url.')';
                    break;
                }
            }
        }
        $md .= implode(' | ', $links)."\n\n";
    }
    $outputs[$root.'/docs/jobsearch/help/'.$locale.'.md'] = $md;
}
$check = in_array('--check',$argv,true);
foreach ($outputs as $path=>$content) {
    if ($check) {
        if (!is_file($path) || str_replace("\r\n","\n",file_get_contents($path)) !== $content) { throw new RuntimeException('Stale generated file: '.$path); }
    } else { file_put_contents($path,$content); }
}
echo ($check?'Verified':'Generated').' '.count($source['topics']).' topics in '.count($source['locales'])." locales\n";
