<?php
declare(strict_types=1);
$root = dirname(__DIR__);
$php = str_replace("\r\n","\n",file_get_contents($root.'/public/index.php'));
$header = "<!-- Generated by tools/build_reference.php; do not edit by hand. -->\n\n";
$schema = "# Datenbankreferenz\n\n".$header;
$schema .= "Stand: 2026-09-03, Zielstand 1.18.1. Diese Referenz enthaelt Schema, historische Migrationen und Runtime-Erweiterungen. Sie ist KEIN gemeinsam ausfuehrbares Installationsskript.\n\n";
$schema .= "Neuaufbau: 01_schema.sql als Basis, danach die idempotenten Runtime-Erweiterungen kontrolliert pruefen. Historische ALTER-Dateien nicht blind erneut anwenden. 02_views.sql ist Altbestand: v_calendar_items projiziert alte next_action-Felder und ist NICHT die aktuelle Kalenderlogik. Siehe REBUILD.md und WORKFLOW.md.\n\n";
foreach (glob($root.'/sql/jobsearch/*.sql') as $path) {
    $schema .= '## '.basename($path)."\n\n```sql\n".trim(file_get_contents($path))."\n```\n\n";
}
$schema .= "## Zusaetzliche Runtime-DDL\n\nOriginale PHP-Stringliterale; nur statische DDL, keine produktiven Daten. Die PHP-Notation und gegebenenfalls Interpolation sind vor einer manuellen Ausfuehrung auf SQL aufzuloesen.\n\n";
$ddl=[];
foreach (token_get_all($php) as $token) {
    if (is_array($token) && $token[0] === T_CONSTANT_ENCAPSED_STRING && preg_match('/(?:CREATE TABLE|ALTER TABLE)/i',$token[1])) {
        $ddl[$token[1]] = true;
    }
}
foreach (array_keys($ddl) as $literal) { $schema .= "```php\n".$literal."\n```\n\n"; }
$schema .= "## Bedingte Spalten und Index-Erweiterungen\n\n";
foreach (explode("\n",$php) as $line) {
    if (preg_match('/^\s+(?:ensureColumn|ensureIndex|modifyColumnWhenMissingValue)\(\$db,/', $line)) {
        $schema .= "```php\n".trim($line)."\n```\n\n";
    }
}
$api = "# Schnittstelleninventar\n\n".$header;
$api .= "Stand: 2026-09-03. Statische Code-Inventur, kein Nachweis der Erreichbarkeit oder Autorisierung eines Endpunkts. Die fachlichen Vertraege stehen in PROGRAMMDOKUMENTATION.md und WORKFLOW.md. Alle POST-Aktionen benoetigen CSRF-Pruefung; weitere Berechtigungen werden im jeweiligen Handler geprueft.\n\n";
foreach (['page'=>'GET-Seiten und Exportendpunkte','action'=>'POST-Aktionen'] as $variable=>$label) {
    preg_match_all('/\$'. $variable .'\s*===\s*[\x27\"]([a-z0-9_]+)[\x27\"]/',$php,$matches);
    $values=array_unique($matches[1]); sort($values);
    $api .= '## '.$label."\n\n";
    foreach ($values as $value) { $api .= '- `'.$value."`\n"; }
    $api .= "\n";
}
$api .= "## Formularfeldnamen\n\nStatische name-Attribute; dynamische Felder muessen am jeweiligen Formular ergaenzt werden. Werte sind bewusst nicht enthalten.\n\n";
preg_match_all('/\bname="([a-z][a-z0-9_\[\]]*)"/',$php,$matches);
$names=array_unique($matches[1]);sort($names);
$api .= implode(', ',array_map(static fn($name)=>'`'.$name.'`',$names))."\n\n";
$api .= "## Funktionssignaturen\n\n";
preg_match_all('/^function [^{]+/m',$php,$matches);
foreach ($matches[0] as $signature) { $api .= '- `'.preg_replace('/\s+/',' ',trim($signature))."`\n"; }
$outputs=[$root.'/docs/jobsearch/DATA_MODEL.md'=>$schema,$root.'/docs/jobsearch/INTERFACES.md'=>$api];
foreach($outputs as $path=>$content) {
    $content = str_replace("\r\n", "\n", $content);
    $content = preg_replace('/[ \\t]+$/m', '', $content);
    if(in_array('--check',$argv,true)) {
        if(!is_file($path)||str_replace("\r\n","\n",file_get_contents($path))!==$content) { throw new RuntimeException('Stale reference: '.$path); }
    } else { file_put_contents($path,$content); }
}
echo "Database and interface references generated/verified\n";
